"""add remito items table

Revision ID: 3ff551f43d6a
Revises: d426cc4a54e6
Create Date: 2026-03-31 21:21:38.468643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff551f43d6a'
down_revision = 'd426cc4a54e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remito_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remito_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['remito_id'], ['remito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remito_item')
    # ### end Alembic commands ###
